package rules

import sharry.WeekTranslator;

rule "day1"
    no-loop true
    when
        wt:WeekTranslator(day == 1)
    then
        wt.setCnName("星期一");
        wt.setEnName("Monday");
        update(wt);
end

rule "day2"
    no-loop true
    when
        wt:WeekTranslator(day == 2)
    then
        wt.setCnName("星期二");
        wt.setEnName("Tuesday");
        update(wt);
end

rule "day3"
    no-loop true
    when
        wt:WeekTranslator(day == 3)
    then
        wt.setCnName("星期三");
        wt.setEnName("Wednesday");
        update(wt);
end

rule "day4"
    no-loop true
    when
        wt:WeekTranslator(day == 4)
    then
        wt.setCnName("星期四");
        wt.setEnName("Thursday");
        update(wt);
end

rule "day5"
    no-loop true
    when
        wt:WeekTranslator(day == 5)
    then
        wt.setCnName("星期五");
        wt.setEnName("Friday");
        update(wt);
end

rule "day6"
    no-loop true
    when
        wt:WeekTranslator(day == 6)
    then
        wt.setCnName("星期六");
        wt.setEnName("Saturday");
        update(wt);
end

rule "day7"
    no-loop true
    when
        wt:WeekTranslator(day == 7)
    then
        wt.setCnName("星期天");
        wt.setEnName("Sunday");
        update(wt);
end